# Generated by Django 2.2 on 2019-04-16 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20190416_0653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['module']},
        ),
    ]
