# Generated by Django 2.2 on 2019-04-17 15:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0002_auto_20190417_1457'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseComment',
            new_name='CourseComments',
        ),
    ]
